cpu.h File Reference
cpu.h File Reference
#include <stdint.h>
Functions
uint32_t CPU_cpsid (void)
uint32_t CPU_cpsie (void)
uint32_t CPU_primask (void)
void CPU_wfi (void)
uint32_t CPU_basepriGet (void)
void CPU_basepriSet (uint32_t newBasepri)
Function Documentation
uint32_t CPU_cpsid (void)
Referenced by Interrupt_disableMaster().
uint32_t CPU_cpsie (void)
uint32_t CPU_primask (void)
Referenced by FlashCtl_eraseSector(), FlashCtl_performMassErase(), FlashCtl_programMemory(), and FlashCtl_verifyMemory().
void CPU_wfi (void)
Referenced by PCM_gotoLPM0(), PCM_gotoLPM3(), and PCM_shutdownDevice().
uint32_t CPU_basepriGet (void)
Referenced by Interrupt_getPriorityMask().
void CPU_basepriSet (uint32_t newBasepri)
Referenced by Interrupt_setPriorityMask().
Copyright 2016, Texas Instruments Incorporated